# Copyright 2019-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0
version: "3"

services:
  onos:
    image: registry.aetherproject.org/tost/tost:int-dev
    # There's something wrong with docker compose in node2
    # Without network_mode host, onos cannot reach the switch
    # It works when doing just docker run, but not via compose
    network_mode: host
    volumes:
      - ./tmp/onos:/root/onos/apache-karaf-4.2.9/data/tmp
    ports:
      - "8181:8181" # HTTP
      - "8101:8101" # SSH (CLI)
